export interface ICountry{
  name: string,
  topLevelDomain: any,
  alph2Code: string,
  alph3Code: string,
  callingCode: any,
  capital: string,
  altSpellings: any,
  region: string,
  subregion: string,
  population: number,
  latlng: any,
  domonym: string,
  area: number,
  gini: number,
  timezones: any,
  borders: any,
  nativeName: string,
  numericCode: number,
  currencies: any,
  languages: any,
  translations: any,
  flag: string,
  regionBlocs: any,
  cioc: string
}
